105 Working e2e tests

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -70,22 +70,40 @@ jobs:
 
       # New Step: Start application
       - name: Start application
-        run: docker run -d -p 8081:8081 --name order-app $(docker images -q | head -n 1)
+        run: docker run -d -p 8081:8081 --name order-app $(docker images 'docker.io/library/order:*' --format '{{.Repository}}:{{.Tag}}' | head -n 1)
 
-      # New Step: Wait for application to start with a multi-line script as above
+      # # New Step: Wait for application to start with a multi-line script as above
+      # - name: Wait for application to start
+      #   run: |
+      #     timeout=300
+      #     while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 | grep -q "200"
+      #     do
+      #       if [ $timeout -le 0 ]; then
+      #         echo "Application failed to start"
+      #         exit 1
+      #       fi
+      #       echo "Waiting for application to start..."
+      #       sleep 5
+      #       timeout=$((timeout - 5))
+      #     done
+
       - name: Wait for application to start
         run: |
           timeout=300
-          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 | grep -q "200"
+          while [ $timeout -gt 0 ]
           do
-            if [ $timeout -le 0 ]; then
-              echo "Application failed to start"
-              exit 1
+            response=$(curl -s -o /dev/null -w "%{http_code}" http://localhost:8081)
+            echo "Response code: $response"
+            if [[ $response == "200" ]]; then
+              echo "Application is ready!"
+              exit 0
             fi
-            echo "Waiting for application to start..."
+            echo "Waiting for application to start... Timeout in $timeout seconds"
             sleep 5
             timeout=$((timeout - 5))
           done
+          echo "Application failed to start within the timeout period"
+          exit 1
 
       # # New Step: Wait for application startup
       # - name: Wait for application startup
