105 Working e2e tests

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -72,24 +72,24 @@ jobs:
       - name: Start application
         run: docker run -d -p 8081:8081 --name order-app $(docker images -q | head -n 1)
 
-      # # New Step: Wait for application to start with a multi-line script as above
-      # - name: Wait for application to start
-      #   run: |
-      #     timeout=300
-      #     while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 | grep -q "200"
-      #     do
-      #       if [ $timeout -le 0 ]; then
-      #         echo "Application failed to start"
-      #         exit 1
-      #       fi
-      #       echo "Waiting for application to start..."
-      #       sleep 5
-      #       timeout=$((timeout - 5))
-      #     done
+      # New Step: Wait for application to start with a multi-line script as above
+      - name: Wait for application to start
+        run: |
+          timeout=300
+          while ! curl -s -o /dev/null -w "%{http_code}" http://localhost:8081 | grep -q "200"
+          do
+            if [ $timeout -le 0 ]; then
+              echo "Application failed to start"
+              exit 1
+            fi
+            echo "Waiting for application to start..."
+            sleep 5
+            timeout=$((timeout - 5))
+          done
 
-      # New Step: Wait for application startup
-      - name: Wait for application startup
-        run: sleep 30
+      # # New Step: Wait for application startup
+      # - name: Wait for application startup
+      #   run: sleep 30
 
       # New Step: Run tests
       - name: Run tests
